import React from "react";
import styles from "./RecentReviewSection.module.css";
import ThumbsUp from '../../assets/Icons/Illustrated/Thumbs up.svg';
import SectionHeader from "../../Components/Shared/SectionHeader";
import ReviewCard from "../../Components/Shared/ReviewCard";

const RecentReviewSection = () => {
  return (
    <div className={styles.section}>
      <SectionHeader headerTitle={"Recently Reviewed"} icon={ThumbsUp}/>
      <div className={styles.reviewCards}>
        <ReviewCard ReviewerName={`Marion Ngayi`} ReviewDate={`12 May 2024`} ReviewerPhoto={`https://res.cloudinary.com/excit3/image/upload/v1718726067/Boltshift%20Branding/Marion_Ngayi_Profile_Picture_jahbhr.png`} Review={`Amazing product! Exceeded my expectations in every way. The quality is top-notch, and the attention to detail is evident in every aspect. I was particularly impressed with the durability and sleek design. It's clear that a lot of thought went into making this product both functional and aesthetically pleasing. The customer service was also exceptional. I had a few questions before purchasing, and the support team was very responsive and helpful. Highly recommend this product to anyone looking for something reliable and stylish.`} ProductImage={`https://i.pinimg.com/564x/2e/99/46/2e994666461707ffd4c535c437abbd5d.jpg`} ProductNameLabel={`Elluis - Pearls Decor Ruffle Hem Stiletto Sandals with Elegant Design - Apricot`} PriceLabel={`104,999`} />
        <ReviewCard ReviewerName={`Wendy Hawi`} ReviewDate={`18 Apr 2024`} ReviewerPhoto={`https://res.cloudinary.com/excit3/image/upload/v1718702112/Boltshift%20Branding/IMG-20240618-WA0001_wzvvd9.jpg`} Review={`I am very pleased with my purchase. The product performs excellently and meets all my expectations. The customer service team was extremely responsive and helpful. Overall, the product works great, and I highly recommend it, especially due to the company's outstanding customer service.`} ProductImage={`https://i.pinimg.com/564x/53/bd/a9/53bda91b1ac49294da1f1edfae7b17a1.jpg`} ProductNameLabel={`Women's Chronograph Ritz Two-Tone Stainless Steel Bracelet Watch`} PriceLabel={`782,099`} />
        <ReviewCard ReviewerName={`Felix Ouma`} ReviewDate={`05 Mar 2024`} ReviewerPhoto={`https://res.cloudinary.com/excit3/image/upload/v1718710477/Boltshift%20Branding/Profile_image_amu6ca.jpg`} Review={`Outstanding product and service! The product is exactly as described and works flawlessly. The design is sleek, and the materials used are of very high quality. I had a minor issue with the setup, but the customer service team was extremely helpful and walked me through the process step-by-step. The shipping was also very fast, and the product arrived well-packaged. I would highly recommend this product to anyone looking for a reliable and high-quality option.`} ProductImage={`https://i.pinimg.com/564x/c5/a5/21/c5a52138ac230fd578c15cd67d094d86.jpg`} ProductNameLabel={`Ergonomic Office Chair with Lumbar Support & Headrest & Flip-up Arms Rocking Home Office Desk Swivel High Back Computer Chair`} PriceLabel={`221,099`}/>
        <ReviewCard ReviewerName={`Vonette Orinda`} ReviewDate={`01 Jun 2024`} ReviewerPhoto={`https://res.cloudinary.com/excit3/image/upload/v1718726170/Boltshift%20Branding/Screenshot_2024-06-18_at_01.05.13_elm0ym.png`} Review={`Good quality and fast shipping. Will buy again. The product arrived well-packaged and in perfect condition. I was pleasantly surprised by the speed of delivery, especially considering the current shipping delays affecting many companies. The product itself is of excellent quality, with sturdy materials and a well-thought-out design. It has become an essential part of my daily routine. The user manual was clear and easy to follow, which made setup a breeze. Overall, a fantastic purchase that I would recommend to others.`} ProductImage={`https://i.pinimg.com/564x/3a/26/e9/3a26e985b2a67f242e4b756eeedab129.jpg`} ProductNameLabel={`Elluis - Contemporary Quilted Satchel Bag with Colorblock Design and Magnetic Closure - green, One Size`} PriceLabel={`12,985`} />
        <ReviewCard ReviewerName={`Kalah Papa`} ReviewDate={`25 May 2024`} ReviewerPhoto={`https://i.pinimg.com/564x/35/74/ed/3574ed0ad69100dc6fa834b74e7d7fc6.jpg`} Review={`Excellent customer service. They resolved my issue quickly and efficiently. I initially had some trouble with my order, as I received the wrong item. However, the customer service team was incredibly helpful and resolved the issue promptly. They arranged for a replacement to be sent out immediately and even provided a discount on my next purchase as a gesture of goodwill. The replacement product is fantastic - high quality, exactly as described, and it works perfectly. I am very pleased with my experience and will definitely be a returning customer.`} ProductImage={`https://i.pinimg.com/564x/68/2a/2f/682a2fd7ba469ffe513fbd9862bab1c2.jpg`} ProductNameLabel={`Sony PlayStation DualSense Edge wireless controller for PS5 has a customizable design`} PriceLabel={`15,000`} />
      </div>
    </div>
  );
};

export default RecentReviewSection;
